# Coloring annotation file for /Users/myd/thesis/project/nutch/parsePaperMetadata/annotation/annotated_repository/http+^^intelligentenvironments.org^conferences^ie09^programme_2009-08-05__14-25-59.yaml created on Wed Aug 05 17:31:19 +0800 2009 
# Coloring version 1.6
Spans:
  - 
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - na
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - authorWithAffiliation
  - title
  - author
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - authorWithAffiliation
  - na
  - na
  - title
  - authorWithAffiliation
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - na
  - na
  - na
  - title
  - authorWithAffiliation
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - title
  - author
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
  - na
